"""auto generating

Revision ID: 250bbdcae191
Revises: c5319e6b2b77
Create Date: 2023-04-24 07:56:43.440607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250bbdcae191'
down_revision = 'c5319e6b2b77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('languages', sa.String(), nullable=False),
    sa.Column('referedby', sa.String(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_email'), 'driver', ['email'], unique=True)
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=False)
    op.create_index(op.f('ix_driver_phone'), 'driver', ['phone'], unique=True)
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('licenseplate', sa.String(), nullable=False),
    sa.Column('Driverid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Driverid'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    op.create_table('referralcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refferalcode', sa.Integer(), nullable=False),
    sa.Column('Driverid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Driverid'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referralcode_id'), 'referralcode', ['id'], unique=False)
    op.create_index(op.f('ix_referralcode_refferalcode'), 'referralcode', ['refferalcode'], unique=True)
    op.drop_table('Driver')
    op.create_foreign_key(None, 'Document', 'driver', ['Driverid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Document', type_='foreignkey')
    op.create_table('Driver',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Driver_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Driver_pkey')
    )
    op.drop_index(op.f('ix_referralcode_refferalcode'), table_name='referralcode')
    op.drop_index(op.f('ix_referralcode_id'), table_name='referralcode')
    op.drop_table('referralcode')
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_driver_phone'), table_name='driver')
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_index(op.f('ix_driver_email'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
